"""empty message

Revision ID: b5b92f99d870
Revises: 
Create Date: 2020-03-09 16:35:51.975680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b92f99d870'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('accountId', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('accountId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profile',
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('birtday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('accountId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('profileId'),
    sa.UniqueConstraint('accountId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('account')
    # ### end Alembic commands ###
