"""empty message

Revision ID: d2db6dbbf643
Revises: b5b92f99d870
Create Date: 2020-03-09 18:22:54.003081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2db6dbbf643'
down_revision = 'b5b92f99d870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('accountId', table_name='profile')
    op.drop_table('profile')
    op.drop_index('email', table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('accountId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('accountId'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('email', 'account', ['email'], unique=True)
    op.create_table('profile',
    sa.Column('profileId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bio', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('birtday', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('accountId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('profileId'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('accountId', 'profile', ['accountId'], unique=True)
    # ### end Alembic commands ###
